version: '3'

services:
  web:
    restart: "on-failure"
     
  nginx:
    restart: "on-failure"


  mysql:
    restart: always
    image: mysql:5.7
    container_name: 'mysql'
    environment:
      MYSQL_DATABASE: 
      MYSQL_USER: ${USER_NAME}
      MYSQL_PASSWORD: ${PASSWORD}
     

    

